openapi: 3.0.3

info:
  title: User Profile Service API
  description: API для профиля пользователя
  version: 1.0.0

servers:
  - url: http://localhost:8081

tags:
  - name: UserProfile
    description: Операции с профилем пользователя

paths:

  /api/user-profiles/{userId}:
    get:
      tags: [ UserProfile ]
      summary: Получить профиль пользователя по userId
      operationId: getUserProfile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Профиль найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileDto'
        '404':
          description: Профиль не найден

    put:
      tags: [ UserProfile ]
      summary: Создать или обновить профиль пользователя
      operationId: putUserProfile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - loyaltyLevel
                - externalBalance
              properties:
                loyaltyLevel:
                  type: string
                  example: PLATINUM
                externalBalance:
                  type: number
                  format: double
                  example: 2000.00
      responses:
        '200':
          description: Профиль создан или обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileDto'

components:
  schemas:
    UserProfileDto:
      type: object
      required:
        - userId
        - loyaltyLevel
        - externalBalance
      properties:
        userId:
          type: string
          format: uuid
        loyaltyLevel:
          type: string
          example: GOLD
        externalBalance:
          type: number
          format: double
          example: 1250.50
